### ISSUE TITLE
Database Mapping

### ISSUE THREAD

**Issue by DiGwork** [projectknife/Projectfork#1615]
Hi would someone please let me have the matching Database Mapping for PF4. I would like to design forms to automatically populate PF Tasks but I need to know what the database mapping is  for all the potential fields used in PF.

**Comment by HelgeSverre** [comment]
Does this relate to the issue you opened in february [Issue #1540](https://github.com/projectfork/Projectfork/issues/1540)?

If so see my response to that issue.

Otherwise, could you be more specific of what you need exactly, if you need an overview over which columns and tables do what I can provide that to you, at least for the projects, tasks, tasklist and milestone columns.

**Comment by DiGwork** [comment]
Yes Thanks HeigeSverre. Unfortunately there is no budget left in the project so I need to hammer on alone. I figured I could make the connections if I just had the Database Mapping fields are for the specific fields in ProjectFork4. But if I don't come right on my own I will contact you.
