### ISSUE TITLE
Is there any form of support left for Projectfork?

### ISSUE THREAD

**Issue by stephenhadden** [projectknife/Projectfork#1679]
I see projectfork is still for purchase, but it seems there is no support? Does Kyle or Tobias still check this stuff out?

**Comment by mbrown1408** [comment]
Based on my waiting period...I'd vote no :-1:

**Comment by mc-cm** [comment]
unfortunately I have to agree on this

**Comment by ssnobben** [comment]
Maybe you can reach out to Tobias here  https://twitter.com/tobiaskuhn https://www.linkedin.com/in/tobiaskuhn  https://github.com/eaxs  but I think Kyle leave long time ago https://twitter.com/kyleledbetter but hope someone else jump on board to help Tobias ! :)

https://vimeo.com/80352582

I think this management of a project is not what it should be unfortunately bcs this project have sooo much potential if they did and do this right not forget to make pr/advertising etc...invite more tech people/marketing people to join and work with this as partners/contributors or Projectfork will die!

**Comment by susannanam** [comment]
i was about to buy the pro version when i fortunately came across this discussion and stopped my enthusiasm immediately... i would have loved to launch a nice project with it and was even looking for an experienced pf-programmer to add some additional tasks... how sad that it is all about to die :( i still wait for about two weeks but if nothing changes, i will have to use something else...but i am still hoping :)

**Comment by ssnobben** [comment]
you can still contact Tobias kuhn to add this additional tasks though..

**Comment by susannanam** [comment]
i was about to buy the pro version when i fortunately came across this discussion and stopped my enthusiasm immediately... i would have loved to launch a nice project with it and was even looking for an experienced pf-programmer to add some additional tasks... how sad that it is all about to die :( i still wait for about two weeks but if nothing changes, i will have to use something else...but i am still hoping :)

**Comment by susannanam** [comment]
i did ask him and he said, that he is not available for customizations but that every experienced joomla developer could do so... but most of all, if pf will no longer be supported and updated for future joomla version, what future does any project have? that is my biggest worry at the moment!

**Comment by angek** [comment]
Tobias has never provided customisations for PF but I have been part of the PF community since PF2 days and even released quite a few extensions to PF in the PF3 and early PF4 days. When I had time in the past I would contribute as much as possible with regards to support but my full time work commitments have kept me away from PF until recently.

Now that I have quit my full time job and gone back to contracting I am a lot more flexible with my time and am starting to refocus on PF4 and am available for customisation work.

While this does not answer your specific question about whether PF4 will continue to be maintained, rest assured that if Tobias was to no longer be able or willing to maintain it, he would do the right thing and let the community know. I can't speak on his behalf but I have a lot of vested interest in PF. I have implemented many customised solutions for clients which I still maintain and from that perspective I will not give up on PF.

**Comment by susannanam** [comment]
thanks angek,  this sounds very very promising! can i contact you via email and tell you about the required customisations? :)

**Comment by angek** [comment]
@susannanam of course you can. I can be reached at angek@angekdesign.com.au

**Comment by ssnobben** [comment]
Sounds good :)  http://pfextensions.angekdesign.com.au/#

**Comment by mbrown1408** [comment]
@susannanam 
How did you contact Tobias? I've been trying for a month with no response. I get a fatal error upon saving tasks when an assigned user is set. Makes the product pretty much worthless :/

**Comment by susannanam** [comment]
@mbrown1408 i have contacted him by email.

**Comment by mbrown1408** [comment]
Once he has his money...he goes MIA. I'd strongly suggest another solution,
but that's just a non-tech consumers opinion. Thanks for the info.

**Comment by DiGwork** [comment]
Hi Angek, now that you are back, did you ever get a chance to complete that RS Form pro PF integration Plugin you started to look at for me early last year.The client I was attempting to build the solution for lost patience and finally lost patience and dropped the project, but I still thing that that would be a great plugin for PF. It will allow for quite a bit of customization for clients that need a dumbed down interface.
https://github.com/projectfork/Projectfork/issues/1119
